import type { Metadata } from "next";
import "./globals.css";

import Header from '@/src/widgets/header/index'

export const metadata: Metadata = {
  title: "Code Sage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
